# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.9.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-09-30T13:17:26Z"
  labels:
    app: tools-pod
  name: tools-pod
spec:
  containers:
  - command:
    - /bin/bash
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: tools-pod
    - name: container
      value: oci
    image: default-route-openshift-image-registry.apps-crc.testing/tools/simpler-tools
    name: simpler-tools
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    volumeMounts:
    - mountPath: /mnt/keys
      name: home-lwhite-S1E9-pods-data-keys
    - mountPath: /mnt/data
      name: home-lwhite-S1E9-pods-data-data
    workingDir: /
  - command:
    - /bin/bash
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: tools-pod
    - name: container
      value: oci
    - name: DISTTAG
      value: f32container
    - name: FGC
      value: f32
    image: default-route-openshift-image-registry.apps-crc.testing/tools/data-container
    name: data
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    volumeMounts:
    - mountPath: /mnt/data
      name: home-lwhite-S1E9-pods-data-data
    - mountPath: /mnt/keys
      name: home-lwhite-S1E9-pods-data-keys
    workingDir: /
  volumes:
  - hostPath:
      path: /home/lwhite/S1E9/pods/data/keys
      type: Directory
    name: home-lwhite-S1E9-pods-data-keys
  - hostPath:
      path: /home/lwhite/S1E9/pods/data/data
      type: Directory
    name: home-lwhite-S1E9-pods-data-data
status: {}

