Vagrant.configure(2) do |config|
  config.vm.box = "fedora/33-cloud-base"
  
  config.vm.define :vagrant_tluh_podman do |vagrant_host|
    vagrant_host.vm.hostname = "tluh-podman"
    vagrant_host.vm.provider :libvirt do |domain|
      domain.cpus = 4
      domain.memory = 4096
      domain.nested = true
    end

    vagrant_host.vm.provision "shell", inline: "sudo dnf install -y podman skopeo buildah" 
    vagrant_host.vm.provision "shell", inline: "dnf clean all"
  end

  config.vm.define :vagrant_tluh_docker do |vagrant_host|
    vagrant_host.vm.hostname = "tluh-docker"
    vagrant_host.vm.provider :libvirt do |domain|
      domain.cpus = 4
      domain.memory = 4096
      domain.nested = true
    end

    vagrant_host.vm.provision "shell", inline: "echo installing based on https://docs.docker.com/engine/install/fedora/"
    vagrant_host.vm.provision "shell", inline: "dnf -y install dnf-plugins-core"
    vagrant_host.vm.provision "shell", inline: "dnf config-manager --add-repo " \
      "https://download.docker.com/linux/fedora/docker-ce.repo"
    vagrant_host.vm.provision "shell", inline: "dnf -y install docker-ce docker-ce-cli containerd.io"
    vagrant_host.vm.provision "shell", inline: "systemctl enable --now docker"
    vagrant_host.vm.provision "shell", inline: "dnf clean all"
  end

  config.vm.define :vagrant_tluh_moby do |vagrant_host|
    vagrant_host.vm.hostname = "tluh-moby"
    vagrant_host.vm.provider :libvirt do |domain|
      domain.cpus = 4
      domain.memory = 4096
      domain.nested = true
    end
    
    vagrant_host.vm.provision "shell", inline: "echo installing based on https://fedoramagazine.org/docker-and-fedora-32/ adapted to f33"
#    vagrant_host.vm.provision "shell", inline: "firewall-cmd --permanent --add-interface=docker0"
#    vagrant_host.vm.provision "shell", inline: "systemd reload firewalld"
    vagrant_host.vm.provision "shell", inline: "grubby --update-kernel=ALL --args=\"systemd.unified_cgroup_hierarchy=0\""
    vagrant_host.vm.provision "shell", inline: "dnf -y install moby-engine docker-compose"
    vagrant_host.vm.provision "shell", inline: "systemctl enable --now docker"
    vagrant_host.vm.provision "shell", inline: "dnf clean all"
    vagrant_host.vm.provision "shell", reboot: true
  end

end