#native app -- doesn't work cause h2 can't be compiled native
# FROM registry.access.redhat.com/ubi8/ubi-minimal
# WORKDIR /work/
# COPY target/*-runner /work/application
# RUN chmod 775 /work
# EXPOSE 8080
# CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]


#uber-jar
FROM registry.redhat.io/openjdk/openjdk-11-rhel7
COPY target/inventory-quarkus-1.0.0-SNAPSHOT-runner.jar inventory-quarkus-runner.jar
COPY runit.sh runit.sh
EXPOSE 8080

CMD ["/home/jboss/runit.sh"]
