apiVersion: v1
items:
- apiVersion: v1
  data:
    COMPONENT_GATEWAY_HOST: Z2F0ZXdheS1jb29sc3RvcmU=
    COMPONENT_GATEWAY_PORT: ODA4MA==
  kind: Secret
  metadata:
    annotations:
      app.kubernetes.io/component-source-type: local
      component-port: "8080"
    labels:
      app: coolstore
      app.kubernetes.io/instance: gateway
      app.kubernetes.io/managed-by: odo
      app.kubernetes.io/managed-by-version: v2.0.4
      app.kubernetes.io/name: dotnet
      app.kubernetes.io/part-of: coolstore
      app.openshift.io/runtime-version: latest
    name: gateway-coolstore-8080
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
